services:
  postgres:
    image: postgres:17-alpine
    container_name: fiji-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fiji}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:24-alpine
    container_name: fiji-clickhouse
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:-fiji}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-user}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-password}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-config/network.xml:/etc/clickhouse-server/config.d/network.xml:ro
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  clickhouse-migrations:
    build:
      context: ./clickhouse-migrations
      dockerfile: Dockerfile
    container_name: fiji-clickhouse-migrations
    environment:
      CLICKHOUSE_HOST: http://clickhouse:8123
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:-fiji}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-user}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-password}
    depends_on:
      clickhouse:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiji-app
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-fiji}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      RESEND_API_KEY: ${RESEND_API_KEY}
      CLICKHOUSE_HOST: http://clickhouse:8123
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:-fiji}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-user}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-password}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse-migrations:
        condition: service_completed_successfully

volumes:
  postgres_data:
  clickhouse_data:
